export default {
  COUNTER: {
    ADD: 'COUNTER/ADD',
    SUBSTRACT: 'SUBSTRACT',
  },
  CHARACTER: {
    CHANGE: 'CHARACTER/CHANGE',
  },
  CHARACTER_INPUT: {
    CHANGE: 'CHARACTER_INPUT/CHANGE',
  },
};
